### ISSUE TITLE
Generated source in customer-core/src

### ISSUE THREAD

**Issue by stefan-ka** [Microservice-API-Patterns/LakesideMutual#17]
Hi there ;)

Running LakesideMutual leads to changed Java files in customer-core/src.

Concretely, after running `./run_all_applications.sh`, `git status` gives me several changes:

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   customer-core/src/main/java/com/lm/ccore/Customer.java
	modified:   customer-core/src/main/java/com/lm/ccore/GetCustomerRequest.java
	modified:   customer-core/src/main/java/com/lm/ccore/GetCustomerResponse.java
	modified:   customer-core/src/main/java/com/lm/ccore/ObjectFactory.java
	modified:   customer-core/src/main/java/com/lm/ccore/Profile.java
	modified:   customer-core/src/main/java/com/lm/ccore/package-info.java
```

Maybe this is intended but I would expect that I don't have changes after "just running" the app; generated code should not be committed.
Or: if the source shall be visible for understandability: generate it into a separate source folder (for example src-gen), ignore it in `.gitignore`, and add/commit it with `-f` (force). Thereby you can commit it; but avoid that users/students have local changes after running the app.

Cheers!
Stefan

**Comment by misto** [comment]
I think these are parts of @socadk's experiments with Web Services. Not sure what the state there is, but I think it was never finished and could probably be removed (or moved to a branch).

**Comment by misto** [comment]
I've removed these for now to avoid confusing our users.
