### ISSUE TITLE
Frontend is not able to establish connections to backend services. 

### ISSUE THREAD

**Issue by odidev** [Microservice-API-Patterns/LakesideMutual#25]
Hi Team, 

 

I have tried to deploy all the micro-services over amd64 and arm64 platforms using ```./run_all_applications.sh``` script and docker-compose method. All the services are running but it seems that the frontend is not able to establish a connection to the backend.  It says the backend service is not running. But the spring boot admin page displays all the backend services running. Adding the log and UI as well. 

 

- [Lakeside_docker_compose_logs1.txt](https://github.com/Microservice-API-Patterns/LakesideMutual/files/9205876/Lakeside_docker_compose_logs1.txt)
 

- [Lakeside_script_logs1.TXT](https://github.com/Microservice-API-Patterns/LakesideMutual/files/9205890/Lakeside_script_logs1.TXT)

![Screenshot (33)](https://user-images.githubusercontent.com/40816837/181433058-22593ee1-1203-4ac0-979c-7ce6f76b2955.png)
![Screenshot (34)](https://user-images.githubusercontent.com/40816837/181433064-830b0ac0-4adf-4d08-8197-c1cec65a4482.png)
![Screenshot (35)](https://user-images.githubusercontent.com/40816837/181433066-ea10d0ed-9f6d-4506-bf1e-75a42c868918.png)
![Screenshot (36)](https://user-images.githubusercontent.com/40816837/181433068-b0c9dd0b-302d-46db-981d-e0f008fd0df3.png)

**Comment by odidev** [comment]
I have tried to verify whether the backend services are running or not by using the curl command. It looks like a configuration or security issue. Logs are mentioned below: - 

 

``` 
root@ip-172-31-29-156:~# curl http://localhost:8080
{
  "timestamp" : "2022-08-03T12:33:55.158+00:00",
  "status" : 401,
  "error" : "Unauthorized",
  "path" : "/"
}
root@ip-172-31-29-156:~# curl http://localhost:8090
{
  "timestamp" : "2022-08-03T12:34:09.591+00:00",
  "status" : 404,
  "error" : "Not Found",
  "path" : "/"
}
root@ip-172-31-29-156:~# curl http://localhost:8100
{
  "timestamp" : "2022-08-03T12:43:59.086+00:00",
  "status" : 404,
  "error" : "Not Found",
  "path" : "/"
}
``` 

Also, the spring boot admin page shows all the backend services running. 

![Screenshot (38)](https://user-images.githubusercontent.com/40816837/182623281-b718afd6-282e-4353-9b1d-ab3c730f168a.png)

**Comment by odidev** [comment]
Hi Team, 

 

I have tried to deploy all the services on a local computer on the ubuntu platform using the virtual box and all the services worked fine. Now frontend services are successfully able to communicate to backend services. It looks like all the services are communicating over localhost. But our requirement is that I have to deploy the services over an amazon Linux instance and I have to communicate over the ec2 instance IP. Can you please provide us with some pointers for the same?

**Comment by misto** [comment]
Sorry for the late reply, the team was on vacation. Great to hear that you (almost) got it to work, the frontends use environment variables (defaulting to localhost) to connect to the backends. For example, see the `customer-management-frontend/.env` file:

```
...
REACT_APP_CUSTOMER_SELF_SERVICE_BACKEND=http://localhost:8080
REACT_APP_CUSTOMER_MANAGEMENT_BACKEND=http://localhost:8100
```

If you change these, everything should work.

**Comment by odidev** [comment]
@misto Thanks for your response. The changes you have suggested worked for me. 
Closing this issue and Thanks for your support.

**Comment by odidev** [comment]
Hi Team, 

 

I’m reopening this issue. The policy management service is still not working using the above changes. I have used the docker-compose ```COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -f docker-compose.prod.yml up``` method to build the docker images and deploy the service. I have changed the localhost to the AWS IP from ```policy-management-frontend/.env``` and ```policy-management-frontend/vue.config.js``` files. These changes worked for me when I deployed the services using the ```./run_all_applications.sh```. While using the docker-compose method only the policy management frontend service is not able to communicate to the backend service rest of the services are working perfectly fine.

**Comment by odidev** [comment]
Hi Team, 

Adding a gentle reminder to take a look at the above issue.

**Comment by odidev** [comment]
Hi Team, 

 

The above[ issue](https://github.com/Microservice-API-Patterns/LakesideMutual/issues/25#issuecomment-1216617405) has been resolved, using [this](https://github.com/odidev/LakesideMutual/commit/53395a98302960d55d58f34f96fcaaf31267f930) change. Now, all the services are working fine by using docker-compose method in AWS EC2 instance.  

 

Kindly provide your suggestion on the above commit.

**Comment by misto** [comment]
Thank you for your feedback. Unfortunately, I fail to see why that change is necessary:
```diff
- const policyManagementBackend =
-  window.__ENV ? window.__ENV.VUE_APP_POLICY_MANAGEMENT_BACKEND :
-   process.env.VUE_APP_POLICY_MANAGEMENT_BACKEND
+ const policyManagementBackend = process.env.VUE_APP_POLICY_MANAGEMENT_BACKEND
```
If `window.__ENV` is undefined, it should fall back to the `process.env.VUE_APP_POLICY_MANAGEMENT_BACKEND`.  The `window.__ENV` is required for https://github.com/andrewmclagan/react-env to "inject" environment variables into the frontend code, so I'd rather not remove that. 

In your solution, how did you set the `VUE_APP_POLICY_MANAGEMENT_BACKEND`?

**Comment by odidev** [comment]
> If window.__ENV is undefined, it should fall back to the process.env.VUE_APP_POLICY_MANAGEMENT_BACKEND. The window.__ENV is required for https://github.com/andrewmclagan/react-env to "inject" environment variables into the frontend code, so I'd rather not remove that.

Yes, you are correct. But, while deploying the micro-services using docker-compose on aws instances I found that ```.__ENV.js``` file does not contain the variable ```VUE_APP_POLICY_MANAGEMENT_BACKEND``` due to which policy management frontend services does not get the IP of its backend services. Please find the screenshot below:-

![1](https://user-images.githubusercontent.com/40816837/209101864-f9ce16a2-7e0a-4a9f-9a11-79f64bda509b.png)

When I used the ```./run_all_application.sh``` script to deploy the micro-services ```.__ENV.js``` does get the ```VUE_APP_POLICY_MANAGEMENT_BACKEND``` variable with the IP. In this method policy management is successfully working. Please find the screenshot below: -

![2](https://user-images.githubusercontent.com/40816837/209101966-4cdac4b5-1321-427a-b709-964cd7ce36c7.png)

**Comment by odidev** [comment]
Hi Team,

Adding a gentle reminder to take a look on the above[ comment](https://github.com/Microservice-API-Patterns/LakesideMutual/issues/25#issuecomment-1362605004). Please share your suggestions on the above [changes](https://github.com/Microservice-API-Patterns/LakesideMutual/issues/25#issuecomment-1328872937).

**Comment by odidev** [comment]
Hi Team, 

 

I looked into the issue and found that ```.env``` file is not copied to Dockerfile due to which while running the ```./entrypoint.sh``` file inside the container it creates the ```__ENV.js``` file without the ```VUE_APP_POLICY_MANAGEMENT_BACKEND``` variable inside it. I have modified Dockerfile to copy the ```.env``` file. This change is working fine in AWS ec2 instance.  

 

Kindly review the [commit](https://github.com/odidev/LakesideMutual/commit/2b4c9f200c14d4de3b22a03bade444c0491e0300) and if changes look good, I will raise the PR.

**Comment by misto** [comment]
Hi! Ah, now I understand why it didn't work in the beginning. You've changed these variables in the .env file. When doing cloud deployments, I usually set these as environment variables, and then the .env files are irrelevant. But it doesn't hurt to copy them to the container, so please yes, a Pull Request would be welcome. I have a few other changes pending for the upcoming spring semester, also touching some of the Dockerfiles, but I'll merge them later. Thanks!

**Comment by misto** [comment]
Thank you! And just a heads-up, I'm planning some updates in the coming week. Nothing groundbreaking, some version updates, and simplifications of the Dockerfiles (to get rid of DOCKER_BUILDKIT, which can be annoying to configure on many cloud providers). I will also remove the somewhat broken `docker-compose.yml` file (but the `docker-compose.prod.yml` will stay and be renamed to `docker-compose.yml`). This should make it easier to get started with the application.

**Comment by misto** [comment]
FYI, we've also added some debug information to the page so it's easier to spot the configuration:

<img width="830" alt="image" src="https://user-images.githubusercontent.com/2111/217834343-6452a906-56cb-4802-87b0-2bd13ac206f5.png">
