### ISSUE TITLE
Open whole Project in IDE should index all subprojects 

### ISSUE THREAD

**Issue by joshuabeny1999** [Microservice-API-Patterns/LakesideMutual#32]
Currently if i open the whole folder in Jetbrains IDE with new > import from existing source it does not reconize all subfolder and its projects. I do not want to open each subfolder seperatly and have multiple Windows open of same IDE. 

Nice would then also having running configurations so

Possible solutions:
- commit .idea folder with basic settings (Only solution for IDEA Intellij, but running config would be possible too and it is very popular by students)
- a root pom.xml config which loads all projects in IDE (maybe https://www.baeldung.com/maven-multi-module)

**Comment by misto** [comment]
Hi Joshua, I'm trying to reproduce it, but when I open the parent folder in IntelliJ (version 2023.1.5) I get a popup asking me whether to load all Maven projects:

<img width="429" alt="Screenshot 2023-12-08 at 08 21 47" src="https://github.com/Microservice-API-Patterns/LakesideMutual/assets/2111/39f1d014-a0e0-4ca1-b5ed-fa6442b38bcb">

And then all Maven projects are recognized, I can start them, run their tests, etc.

<img width="341" alt="Screenshot 2023-12-08 at 08 28 52" src="https://github.com/Microservice-API-Patterns/LakesideMutual/assets/2111/1cac1ca6-bdb6-4abd-9e46-c585dc0b556d">

**Comment by joshuabeny1999** [comment]
Hi Mirko

How did you opened it? Maybe I opened it wrong so it does not recognised it. 

I opened it via New > Import project from existing source and had chosen import as maven project.

Kind regards, 
Joshua

**Comment by misto** [comment]
Just File -> Open :-) But I just realized that our instructions in [IDE_INSTRUCTIONS.md](https://github.com/Microservice-API-Patterns/LakesideMutual/blob/master/IDE_INSTRUCTIONS.md) were a bit outdated; we updated them.

**Comment by joshuabeny1999** [comment]
Great, 
Will try it again tonight or tomorrow and report if that working.

**Comment by joshuabeny1999** [comment]
It worked. I guess the documentation confused me so i try to open via project from existing source instead of just File> open.
